#!/bin/bash
set -x

# Create k3s config directory
mkdir -p /etc/rancher/k3s/

# k3s agents join on port 6443.
cat <<EOF > /etc/rancher/k3s/config.yaml
token: "${token}"
server: https://${lb_ip}:6443
EOF

# Set k3s version if specified
if [ ! -z "${k3s_version}" ]; then
  export INSTALL_K3S_VERSION="${k3s_version}"
fi

# Install k3s agent
curl -sfL https://get.k3s.io | sh -s - agent

# Enable and start the k3s agent service.
systemctl enable k3s-agent
systemctl start k3s-agent
